-   id: olivaw-test
    name: Check project fragment
    description: Make a syntax and OWL constraint violation test on the fragments
    entry: olivaw test precommit
    args: [--MODE=PRECOMMIT]
    require_serial: true
    language: python
    additional_dependencies: ['-r', 'requirements-precommit.txt']
    files: \.ttl$|\.rq$
    stages: [commit, push, manual]