name: "Olivaw model test"
author: "Wimmics"
description: "Launches Olivaw model test"
inputs:
  repository:
    description: "The url of the repository to test"
    type: string
    required: true
  ref:
    description: "The ref of the repository to test"
    type: string
    requird: true
  gist-secret:
    description: "The personal access token with only gist scope allowed"
    type: string
    required: true
  server-url:
    description: "The platform URL"
    type: string
    required: false
    default: "https://github.com"
  skip-pass:
    description: "Should the report ignore all the Pass status outcomes"
    type: boolean
    required: false
    default: false
  tested-only:
    description: "Should the report ignore all the NotTested outcomes"
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5 
      with:
        python-version: 'pypy3.9'
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - name: Generate report
      shell: bash
      run: |
        pip install git+https://github.com/Wimmics/olivaw

        olivaw test model --mode=actions --DEV_USERNAME=${{ github.actor }} --REPO_URI=${{ inputs.server-url }}/${{ inputs.repository }} --BRANCH=${{ inputs.ref }}

    - name: Commit the report
      shell: bash
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Olivaw in Actions"
        git add msg.txt
        git commit -m "Provide diagnose [skip actions]"
        git remote set-url origin ${{ inputs.server-url }}/${{ inputs.repository }}
        git push