name: "Olivaw tests"
author: "Wimmics"
description: "Launches Olivaw test suite"
inputs:
  repository:
    description: "The url of the repository to test"
    type: string
    required: true
  ref:
    description: "The ref of the repository to test"
    type: string
    requird: true
  gist-secret:
    description: "The personal access token with only gist scope allowed"
    type: string
    required: true
  model-test:
    description: "Should the model tests be run"
    type: boolean
    required: false
    default: true
  data-test:
    description: "Should the data tests be run"
    type: boolean
    required: true
    default: false
  server-url:
    description: "The platform URL"
    type: string
    required: false
    default: "https://github.com"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5 
      with:
        python-version: 'pypy3.9'
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - name: Generate model test report
      if: $${{ inputs.model-test }}
      shell: bash
      run: |
        pip install git+https://github.com/Wimmics/olivaw@proto-data-test-2

        SUMMARY="$(olivaw test model --mode=actions --DEV_USERNAME=${{ github.actor }} --REPO_URI=${{ inputs.server-url }}/${{ inputs.repository }} --BRANCH=${{ inputs.ref }})"
        TOKENS=($SUMMARY)

        echo "PASS=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
        echo "NOTTESTED=$(echo ${TOKENS[5]})" >> $GITHUB_ENV
        echo "CANNOTTELL=$(echo ${TOKENS[8]})" >> $GITHUB_ENV
        echo "MINORFAIL=$(echo ${TOKENS[11]})" >> $GITHUB_ENV
        echo "MAJORFAIL=$(echo ${TOKENS[14]})" >> $GITHUB_ENV

        echo "EL_LABEL=$(echo ${TOKENS[17]})" >> $GITHUB_ENV
        echo "EL_COLOR=$(echo ${TOKENS[20]})" >> $GITHUB_ENV
        echo "QL_LABEL=$(echo ${TOKENS[23]})" >> $GITHUB_ENV
        echo "QL_COLOR=$(echo ${TOKENS[26]})" >> $GITHUB_ENV
        echo "RL_LABEL=$(echo ${TOKENS[29]})" >> $GITHUB_ENV
        echo "RL_COLOR=$(echo ${TOKENS[32]})" >> $GITHUB_ENV

        echo "GISTID=$(olivaw show gist --mode=actions --DEV_USERNAME=${{ github.actor }} --REPO_URI=${{ inputs.server-url }}/${{ inputs.repository }} --BRANCH=${{ inputs.ref }})" >> $GITHUB_ENV

        REF=${{ inputs.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        echo $BRANCH_NAME
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
        echo "REPO=$(echo $${{ inputs.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

        git add .acimov/output/model-test-actions.ttl .acimov/output/model-test-actions.md -f

    - name: Generate data test report
      shell: bash
      if: ${{ inputs.data-test }}
      run: |
        olivaw test model --mode=actions --DEV_USERNAME=${{ github.actor }} --REPO_URI=${{ inputs.server-url }}/${{ inputs.repository }} --BRANCH=${{ inputs.ref }}
        git add .acimov/output/data-test-actions.ttl .acimov/output/data-test-actions.md -f

    - name: Add output files to repository
      shell: bash
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Olivaw in Actions"
        git commit -m "Provide automatic tests report [skip actions]"
        git remote set-url origin ${{ inputs.server-url }}/${{ inputs.repository }}
        git push

    - name: Archive model test results
      uses: actions/upload-artifact@v3
      with:
        name: model-test-report
        path: .acimov/output/model-test-actions.md

    - name: Create the Pass Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_PASS.json
        label: Pass
        message: ${{ env.PASS }}
        color: green

    - name: Create the NotTested Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_NOTTESTED.json
        label: NotTested
        message: ${{ env.NOTTESTED }}
        color: White

    - name: Create the CannotTell Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_CANNOTTELL.json
        label: CannotTell
        message: ${{ env.CANNOTTELL }}
        color: yellow

    - name: Create the MinorFail Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_MINORFAIL.json
        label: MinorFail
        message: ${{ env.MINORFAIL }}
        color: orange

    - name: Create the MajorFail Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_MAJORFAIL.json
        label: MajorFail
        message: ${{ env.MAJORFAIL }}
        color: red

    - name: Create the OWL_EL Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_EL.json
        label: OWL EL
        message: ${{ env.EL_LABEL }}
        color: ${{ env.EL_COLOR }}

    - name: Create the OWL_QL Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_QL.json
        label: OWL QL
        message: ${{ env.QL_LABEL }}
        color: ${{ env.QL_COLOR }}

    - name: Create the OWL_RL Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ inputs.gist-secret }}
        gistID: ${{ env.GISTID }}
        filename: ${{ env.BRANCH }}_RL.json
        label: OWL RL
        message: ${{ env.RL_LABEL }}
        color: ${{ env.RL_COLOR }}